export const data = [
  {
    id: 0,
    time: "5h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 1,
    time: "2 days ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 2,
    time: "1h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 3,
    time: "20 mins ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 4,
    time: "5h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 5,
    time: "5h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 6,
    time: "5h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 7,
    time: "5h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 8,
    time: "5h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 9,
    time: "5h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 10,
    time: "5h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
  {
    id: 11,
    time: "5h ago",
    schedule: "full time",
    title: "senior software engineeer",
    company: "So Digital, Inc",
    location: "remote",
  },
];
